// <auto-generated />
using System;
using BuildingRegistry.Projections.Wms;
using GeoAPI.Geometries;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuildingRegistry.Projections.Wms.Migrations
{
    [DbContext(typeof(WmsContext))]
    [Migration("20190710194129_AddViews")]
    partial class AddViews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Position");

                    b.HasKey("Name")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("ProjectionStates","wms");
                });

            modelBuilder.Entity("BuildingRegistry.Projections.Wms.Building.Building", b =>
                {
                    b.Property<Guid>("BuildingId")
                        .ValueGeneratedOnAdd();

                    b.Property<IPolygon>("Geometry")
                        .HasColumnType("geometry");

                    b.Property<string>("GeometryMethod")
                        .HasColumnType("varchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Id")
                        .HasColumnType("varchar(46)")
                        .HasMaxLength(46);

                    b.Property<bool>("IsComplete");

                    b.Property<int?>("PersistentLocalId");

                    b.Property<string>("StatusAsText")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset>("VersionTimestampAsDateTimeOffset")
                        .HasColumnName("Version");

                    b.HasKey("BuildingId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("Buildings","wms");
                });

            modelBuilder.Entity("BuildingRegistry.Projections.Wms.BuildingUnit.BuildingUnit", b =>
                {
                    b.Property<Guid>("BuildingUnitId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BuildingId");

                    b.Property<int?>("BuildingPersistentLocalId");

                    b.Property<int?>("BuildingUnitPersistentLocalId");

                    b.Property<string>("Function")
                        .HasColumnType("varchar(21)")
                        .HasMaxLength(21);

                    b.Property<string>("Id")
                        .HasColumnType("varchar(53)")
                        .HasMaxLength(53);

                    b.Property<bool>("IsBuildingComplete");

                    b.Property<bool>("IsComplete");

                    b.Property<IPoint>("Position")
                        .HasColumnType("geometry");

                    b.Property<string>("PositionMethod")
                        .HasColumnType("varchar(22)")
                        .HasMaxLength(22);

                    b.Property<string>("StatusAsText")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset>("VersionTimestampAsDateTimeOffset")
                        .HasColumnName("Version");

                    b.HasKey("BuildingUnitId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("BuildingUnits","wms");
                });

            modelBuilder.Entity("BuildingRegistry.Projections.Wms.BuildingUnit.BuildingUnitBuildingPersistentLocalId", b =>
                {
                    b.Property<Guid>("BuildingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BuildingPersistentLocalId");

                    b.HasKey("BuildingId")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("BuildingPersistentLocalId");

                    b.ToTable("BuildingUnit_BuildingPersistentLocalIds","wms");
                });
#pragma warning restore 612, 618
        }
    }
}
