name: TestS3

on:
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'Informatievlaanderen'
    name: TestS3
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials (Test)
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.VBR_AWS_ACCESS_KEY_ID_TST }}
        aws-secret-access-key: ${{ secrets.VBR_AWS_SECRET_ACCESS_KEY_TST }}
        aws-region: ${{ secrets.VBR_AWS_REGION_PRD }}

    - name: Login to Amazon ECR (Test)
      uses: aws-actions/amazon-ecr-login@v1.5.2

    - name: Prepare file to deploy
      shell: bash
      run: |
        echo Prepare file to deploy
        echo hello > hello.txt
        
    # Deployment of Lambda functions must be done from the Test environment
    - name: Deploy to S3
      if: env.RELEASE_VERSION != 'none'
      shell: bash
      run: |
        echo Deploy to S3
        echo aws s3 cp hello.txt s3://s3-vbr-test-basisregisters-lam-sqsbackofficehandlerfunction
        aws s3 cp hello.txt s3://s3-vbr-test-basisregisters-lam-sqsbackofficehandlerfunction
        